# Generated by Django 2.2.4 on 2020-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='plan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
