# Generated by Django 2.2.4 on 2020-11-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_item_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
